<?php // this is an autogenerated file - do not edit (created Wed, 16 Feb 2011 23:06:48 +0100)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'attribute' => '/Classes/Attribute.php',
            'attributes' => '/Classes/Attributes.php',
            'character' => '/Classes/Character.php',
            'characterlist' => '/Classes/CharacterList.php',
            'characterstat' => '/Classes/CharacterStat.php',
            'check' => '/Classes/Check.php',
            'dice' => '/Classes/Dice.php',
            'saveable' => '/Classes/Saveable.php',
            'sixsider' => '/Classes/SixSider.php',
            'skill' => '/Classes/Skill.php',
            'skillcheck' => '/Classes/SkillCheck.php',
            'skilllist' => '/Classes/SkillList.php',
            'skillvalue' => '/Classes/SkillValue.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
